version: '3.8'
services:
  postgres-db:
    image: postgres:14-alpine
    container_name: sportnews-postgres-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sportnews_db
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: sportnews-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5055:80"
    depends_on:
      - postgres-db

volumes:
  postgres_data: